kind: Deployment
apiVersion: apps/v1
metadata:
  name: covid-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-dashboard
  template:
    metadata:
      labels:
        app: covid-dashboard
    spec:
      containers:
        - name: covid-dashboard
          image: tflee/covid-dashboard
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: covid-dashboard
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: covid-dashboard